"""empty message

Revision ID: 0908cdb3bd21
Revises: 890b89921ca8
Create Date: 2026-02-14 12:54:35.688531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0908cdb3bd21'
down_revision = '890b89921ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.Enum('video', 'image', 'gif', 'animation', 'document', name='type_multimedia_resources'), nullable=False))
        batch_op.drop_column('type')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point_type', sa.Enum('lesson', 'module', 'course', name='type_user_points'), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('lesson', 'module', 'course', name='type_user_points'), autoincrement=False, nullable=False))
        batch_op.drop_column('point_type')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('stripe_payment_intent_id')

    with op.batch_alter_table('multimedia_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('video', 'image', 'gif', 'animation', 'document', name='type_multimedia_resources'), autoincrement=False, nullable=False))
        batch_op.drop_column('resource_type')

    # ### end Alembic commands ###
