"""empty message

Revision ID: c24925a78f8a
Revises: 5d24f97b4db0
Create Date: 2026-02-09 19:07:40.288220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24925a78f8a'
down_revision = '5d24f97b4db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('courses_description_key'), type_='unique')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('learning_objective',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_lesson_order_per_module', ['module_id', 'order'])
        batch_op.drop_constraint(batch_op.f('lessons_module_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['module_id'], ondelete='CASCADE')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_module_order_per_course', ['course_id', 'order'])
        batch_op.drop_constraint(batch_op.f('modules_course_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['course_id'], ondelete='CASCADE')

    with op.batch_alter_table('multimedia_resources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('multimedia_resources_lesson_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lessons', ['lesson_id'], ['lesson_id'], ondelete='CASCADE')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.create_unique_constraint('uq_user_course_purchase', ['user_id', 'course_id'])
        batch_op.drop_constraint(batch_op.f('purchases_course_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('purchases_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['course_id'], ondelete='RESTRICT')

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_achievement', ['user_id', 'achievement_id'])
        batch_op.drop_constraint(batch_op.f('user_achievements_achievement_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_achievements_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'achievements', ['achievement_id'], ['achievement_id'], ondelete='CASCADE')

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_points_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_lesson_progress', ['user_id', 'lesson_id'])
        batch_op.drop_constraint(batch_op.f('user_progress_lesson_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_progress_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'lessons', ['lesson_id'], ['lesson_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_progress_user_id_fkey'), 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('user_progress_lesson_id_fkey'), 'lessons', ['lesson_id'], ['lesson_id'])
        batch_op.drop_constraint('uq_user_lesson_progress', type_='unique')

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_points_user_id_fkey'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_achievements_user_id_fkey'), 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('user_achievements_achievement_id_fkey'), 'achievements', ['achievement_id'], ['achievement_id'])
        batch_op.drop_constraint('uq_user_achievement', type_='unique')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchases_user_id_fkey'), 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('purchases_course_id_fkey'), 'courses', ['course_id'], ['course_id'])
        batch_op.drop_constraint('uq_user_course_purchase', type_='unique')
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('multimedia_resources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('multimedia_resources_lesson_id_fkey'), 'lessons', ['lesson_id'], ['lesson_id'])

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('modules_course_id_fkey'), 'courses', ['course_id'], ['course_id'])
        batch_op.drop_constraint('uq_module_order_per_course', type_='unique')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lessons_module_id_fkey'), 'modules', ['module_id'], ['module_id'])
        batch_op.drop_constraint('uq_lesson_order_per_module', type_='unique')
        batch_op.alter_column('learning_objective',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('courses_description_key'), ['description'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
